# Generated by Django 2.0.5 on 2018-10-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_auto_20180922_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dp',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
