# Generated by Django 2.0.5 on 2018-10-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_profile_dp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dp',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
    ]
